spring.application.name=actividadIA

spring.datasource.url=jdbc:mysql://localhost:3306/jamaikaejercicio
spring.datasource.username=usr_api_service
spring.datasource.password=BackendPass123!


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ERRORES
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false